### PR TITLE
[TASK] Updates the backend module for TYPO3 7.

### PR DESCRIPTION
**Pull request by echavaillaz**

### CODE REVIEW

**Comment by dmitryd** [comment]
There is a problem: it will break TYPO3 4.5. There are many sites that still use RealURL there.

I suppose the fix will stay here for anybody, who has the issue, to apply manually. Meanwhile realurl v2 will be released soon with new BE module and will not have such issue.

**Comment by echavaillaz** [comment]
There is nothing who will break TYPO3 4.5. I make the check for all changes.

**Comment by dmitryd** [comment]
Namespaces in the code?

**Comment by echavaillaz** [comment]
Ok

**Comment by dmitryd** [comment]
Btw, you can try version 2. It now has Backend modules and it is feature complete.

**Comment by dmitryd** [comment]
Incompatible with 4.5. Please, use realurl 2 instead.

**Pull request closed without merging**
