### PR TITLE
Ignore new Facebook Urlparameter fbclid

### LINKED ISSUE #649: Ignore new Facebook Url Parameter - fbclid

### PR DESCRIPTION
**Pull request by WorksDev**
- Fixes #649

### CODE REVIEW

**Comment by jonaseberledmind** [comment]
Hi @dmitryd,

don't you think it would be better to use the already configured TYPO3 setting for that? So that realurl does not have to be patched (or the site config changed) if another param shall be excluded.




```
...
                'cache' => [
                    'ignoredGetParametersRegExp' => $this->ignoreCHashExcludedParametersRegex(),
                ],
...

    protected function ignoreCHashExcludedParametersRegex()
    {
        return '/^(?:'
            . implode(
                '|',
                array_map(
                    function ($e) {
                        return preg_quote($e, '/');
                    },
                    $GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters']
                )
            )
            . ')$/';
    }
```

in my realurl-hook

**Comment by jonaseberle** [comment]
Please try this: Add a parameter in the Install Tool in ignoreCHashExclude... 
When realurl is enabled, it throws a 404 when the parameter is added to an URL.
When disabled, no 404.

Of course those 2 parameters are linked.

**Comment by dmitryd** [comment]
jonaseberle, I am sure you know realurl better than I do ;)

**Comment by jonaseberle** [comment]
I was just making a suggestion. One addition: exclude L from the list above.

**Comment by dmitryd** [comment]
`L` is already ignored by `CacheHashCalculator` class. There is no need to add it there.

**Pull request merged**
