### PR TITLE
Allow realurl to run on PHP 7.0

### PR DESCRIPTION
**Pull request by Tuurlijk**

### CODE REVIEW

**Comment by dmitryd** [comment]
I am not able to test it with PHP 7.0 yet :(

FYI: no more releases of 1.x are planned because 2.0 will be out any day now.

**Comment by Tuurlijk** [comment]
Here is a pre-built test box for you: https://github.com/Tuurlijk/TYPO3.Homestead

You can test with PHP 5.5, 5.6 and 7.0. On TYPO3 6.2 and 7.6. You can also install any other TYPO3 version to test with.

It's just a 1.5 GB download away.

The problem is that the introduction package depends on realurl 1.x and it does not allow for PHP 7.0. So currently the Homestead box does not have a running Introduction package.

**Comment by Tuurlijk** [comment]
Just updated the Review box too. That's just 1GB: https://github.com/Tuurlijk/TYPO3.Review

**Comment by Tuurlijk** [comment]
The TYPO3 core team uses the Homestead box for development. Currently the Introduction package can not be installed there because of this issue.

**Comment by dmitryd** [comment]
This pull request is for branch 1x. There will be no more releases for 1.x branch. Are you sure you want merge to this branch? Realurl 1.x has multiple issues in TYPO3 7.6+ and they will not be fixed because realurl 2.0 is supposed to replace 1.x soon. The effort to do anything for 1.x will be lost in a couple of days.

**Comment by Tuurlijk** [comment]
Yes, I am completely sure.

**Comment by dmitryd** [comment]
Okay.

**Comment by dmitryd** [comment]
It says PHP 7.999.999. Are you sure the code will be compatible with PHP 7.8 or something like that?

**Comment by Tuurlijk** [comment]
My objective is to fix this version of realur so that the introduction package (which requires this version) will once again work on the development box. The box currently runs PHP 7.0.3.

So I would also be fine with a 7.0.99 constraint.

**Comment by dmitryd** [comment]
Okay, I merged it but supported maximum PHP version is set to 7.0.999.

**Comment by Tuurlijk** [comment]
Thanks man

**Comment by Tuurlijk** [comment]
Can you please tag a release?

**Comment by dmitryd** [comment]
Hm. From above:
> There will be no more releases for 1.x branch.

**Comment by dmitryd** [comment]
That's why I said: there is no point spending time on 1_x. I can tag it but it will not go to TER anyway and it will not be an official tested release. It may NOT go to Intro package because I cannot guarantee it works and it is stable.

All my efforts are on version 2.0 now. This is what introduction package team should be testing and preparing.

**Comment by Tuurlijk** [comment]
I am aware that it will not go to ter. I just need composer to pick it up during box building.

**Comment by dmitryd** [comment]
https://github.com/dmitryd/typo3-realurl/tree/1.13.7

**Comment by Tuurlijk** [comment]
\o/

**Pull request merged**
