### PR TITLE
Adds support for remove of trailing empty segments.

### PR DESCRIPTION
**Pull request by tobiasklepp**
Solves issue #601

### CODE REVIEW

**Comment by davdenic** [comment]
hi @tobiasklepp I'm trying your solution but to me it does not work :(

**Comment by tobiasklepp** [comment]
> 
> 
> hi @tobiasklepp I'm trying your solution but to me it does not work :(

Hi @davdenic, if you like you can use my fork: https://github.com/hope-media/typo3-realurl

**Comment by dmitryd** [comment]
Not acceptable: it changes vendor name space in composer and extension version.

**Comment by dmitryd** [comment]
The fix is incorrect because it removes empty segments from a single postVar, thus breaking the case when there are multiple postVars.

Proper solution for your case would be one of:

* Using `init/emptySegmentValue` configuration option
* Using separate postVars

Since this cannot eb integrated, I close this PR.

**Pull request closed without merging**
