### PR TITLE
[BUGFIX] Wrong redirects for UTF8 URLs after changing configuration #378

### PR DESCRIPTION
**Pull request by mvoehringer**
This is only an example that fixes my issue, to solve the issue speakingUri should be urldecoded global.

### CODE REVIEW

**Comment by dmitryd** [comment]
The problem here is that cache entries should be url encoded for the path part but they were not. This is fixed in https://github.com/dmitryd/typo3-realurl/commit/03906d1d9a4a639f4bb73640786baf8ea4fce14c now.

**Comment by dmitryd** [comment]
Unfortunately it makes old entries invalid and useless now :(

**Comment by mvoehringer** [comment]
Good news, that you fixed this problem. Loosing all the old urls is not a good news, what is the problem with these old urls? Is the problem, that all the urls are encoded in the cache after you update (like it was in older realurl versions)?

**Comment by dmitryd** [comment]
@mvoehringer Yes, they are not encoded in the cache. I am currently thinking of making an update procedure for such entries but I need to find reliable way to detect them. And it can timeout because it can take a lot of time if there are many entries.

The best way is to clear FE cache. Pages will be regenerated as well as urls.

**Comment by dmitryd** [comment]
See also https://github.com/dmitryd/typo3-realurl/commit/ef79bf76197561ce73d5e1559926938a45fd5cfa

**Comment by dmitryd** [comment]
@mvoehringer The update wizard is integrated now.

**Pull request closed without merging**
