### PR TITLE
[FEATURE] added a hook for post-processing the configuration 

### PR DESCRIPTION
**Pull request by p2media**
We needed a simple hook to modify the configuration

### CODE REVIEW

**Comment by BenjaminBeck** [comment]
Why not use Signal/Slot mechanism?
- http://stackoverflow.com/questions/30544422/typo3-extbase-how-to-use-core-signal-slots
- https://forge.typo3.org/issues/59089

**Comment by dmitryd** [comment]
@BenjaminBeck RealURL uses traditional hooks in other part due to compatibility. Mixing traditional hooks with signals would not be a good idea.

**Comment by BenjaminBeck** [comment]
Ok, Thank your for the explanation

**Comment by dmitryd** [comment]
I think you would also want to know what mode are you running in: decode or encode. Probably adding a getter for the `ConfigurationReader::$mode` make sense.

**Comment by p2media** [comment]
Yes, that was a dumb idea 😅  
I've removed `mode` from the parameters and added a proper getter function `getMode()`

**Comment by dmitryd** [comment]
Thank you for your work!

**Pull request merged**
