### PR TITLE
Better cope with missing chashcache entries

### PR DESCRIPTION
**Pull request by cweiske**
The problem is fully described in
https://github.com/dmitryd/typo3-realurl/issues/245

Resolves: #245

### CODE REVIEW

**Comment by dmitryd** [comment]
No, this is not a correct solution. Realurl only encodes and decodes URLs. It should not handle cache issues.

**Comment by cweiske** [comment]
> Realurl only encodes and decodes URLs. It should not handle cache issues.

But who if not realurl is responsible for the cache tables that realurl fills?

**Comment by dmitryd** [comment]
> But who if not realurl is responsible for the cache tables that realurl fills?

That's right. And you should not go and truncate them because it is realurl's job, not yours :) Would you like if somebody comes to your computer and wipes your documents without a warning (like bank access codes) and than demand to recover from it? Probably not. Realurl tables belong to realurl. It is valuable data and it should not be manipulated by anybody in any way.

**Comment by cweiske** [comment]
I think we can stop discussing now since we have different views on this issue. Thanks for maintaining realurl.

**Pull request closed without merging**
