### PR TITLE
[TASK] Add svg icons for extension and backend module

### PR DESCRIPTION
**Pull request by jousch**
Since TYPO3 CMS 8.3, extension icons should/could be moved to
Resources/Public/Icons/Extension.svg. I therefore created an svg icon
of your actual "pill icon".

The backend module actually works with TYPO3 CMS 7.6 and above.
An svg version of the icon could be added therefore. I suggested to slightly
modify it by adding a background and removing the drop shadow.

### CODE REVIEW

**Comment by jousch** [comment]
image

image

**Comment by faulancr** [comment]
i would suggest to reduce the icon to a more reduced version. 
[realurl_icon.svg.zip](https://github.com/dmitryd/typo3-realurl/files/545689/realurl_icon.svg.zip)
bildschirmfoto 2016-10-22 um 10 49 54

**Comment by jousch** [comment]
@faulancr They look nice! I like v2.

@dmitryd, what do you think about? I also can imagine an icon with a text in the icon like "/url/".

**Comment by dmitryd** [comment]
@jousch Wow, that pill looks cool :) While @faulancr icons looks more in TYPO3 style, I still like the pill more. Let me think. One of these definitely should be integrated. Or both. May be, pill for one release and that link icon since the second release from now. I really want to see that cool pill first :)

**Comment by faulancr** [comment]
@dmitryd the go with version 2 ;) The Linkchain looks quite similar to the pill.

**Comment by dmitryd** [comment]
realurl_icon.svg.zip looks more in TYPO3 style. What do you all think?

**Comment by jeremieroulin** [comment]
I vote for realurl_icon_3.svg.zip! :)

**Comment by faulancr** [comment]
the reason i put a speaking bubble into it, is that the chain is more a symbol for "link" than for "url", which in the end is quite similar but not the same.

**Comment by dmitryd** [comment]
Hm. Let's make a vote through twitter :)

https://twitter.com/dmitryd/status/792431489459838978

**Comment by dmitryd** [comment]
I could not leave those two icons. So I added them too and made possible to select them for the module :)

**Pull request merged**
